### ISSUE TITLE
Adding CKAN user to the public catalogue fails due to non-ASCII characters

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/open-data-node#150]
When I wanted to install ODN 1.0.2, the installation failed on adding a CKAN user to the public catalogue:

```
>> add_odn_ckan_pc_user
Traceback (most recent call last):
  File "/usr/share/python/odn-ckan-shared/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/share/python/odn-ckan-shared/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/share/python/odn-ckan-shared/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/share/python/odn-ckan-shared/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/share/python/odn-ckan-shared/local/lib/python2.7/site-packages/ckan/lib/cli.py", line 783, in command
    self.search()
  File "/usr/share/python/odn-ckan-shared/local/lib/python2.7/site-packages/ckan/lib/cli.py", line 838, in search
    print self.get_user_str(user)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0159' in position 23: ordinal not in range(128)
dpkg: error processing odn-simple (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 odn-simple
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

As the traceback indicates, the error is caused by non-ASCII characters ("ř") that cannot be serialized. This suggests that it is a bug in CKAN. We should investigate what is the root cause of this problem and report it upstream to CKAN maintainers if it turns out to be a generic issue.

**Comment by skrchnavy** [comment]
Priority downgraded, this is not critical. Workaround is to use ascii chars in names.

**Comment by jindrichmynarz** [comment]
I believe this is a problem of the vanilla instance of ODN, which probably uses some non-ASCII characters in user names. While it may be a CKAN's bug, we should check if ODN installer does not create non-ASCII user names. If that's the case, it's a high-priority bug because it makes ODN 1.0.2 installation fail.

@Jan-Marcek, can you please comment, where the non-ASCII characters might come from?
