### ISSUE TITLE
Could not obtain dataset

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/open-data-node#153]
A user is logged as casadmin. the user runs a pipeline with DPU - uv-l-filesToCkan via ckan.
The pipeline execution fails. - it was run as admin. It should be run as casadmin

When the user executes the pipeline manually from unifiedviews then it successfully finishes. In this case unifiedviews executes the pipeline as casadmin.

```
Execution failed because: Could not obtain dataset from CKAN.eu.unifiedviews.dpu.DPUException: Could not obtain dataset from CKAN.
at eu.unifiedviews.helpers.dpu.context.ContextUtils.dpuException(ContextUtils.java:181)
at eu.unifiedviews.plugins.loader.filestockan.FilesToCkan.innerExecute(FilesToCkan.java:197)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by Jan-Marcek** [comment]
resolved by https://github.com/UnifiedViews/Core/commit/c65a6aebb21fcef85e410dc15a061f3b962e8daa

**Comment by Jan-Marcek** [comment]
might be related https://github.com/OpenDataNode/open-data-node/issues/127
