### ISSUE TITLE
Import/Export of pipeline is not working between odn1.0.3 to 1.1.0

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/open-data-node#165]
Steps:
1. Export a pipeline to odn@1.0.3 
2. Import the pipeline to odn@1.1.0 

UV in Version 2.1.0

```
2015-07-10 12:24:57,804 [ajp-bio-28009-exec-2] ERROR c.c.m.x.o.c.app.pipeline.transfer.ImportService - Missing or wrong pipeline file
2015-07-10 12:24:57,807 [ajp-bio-28009-exec-2] ERROR c.c.m.xrg.odcs.frontend.gui.dialog.PipelineImport - reading of pipeline from zip: /tmp/tomcat7-unifiedviews-frontend-tmp/jarDPU3623094018241756732/SA P- Protected sites.zip failed
cz.cuni.mff.xrg.odcs.commons.app.pipeline.transfer.ImportException: Missing or wrong pipeline file
        at cz.cuni.mff.xrg.odcs.commons.app.pipeline.transfer.ImportService.loadPipeline(ImportService.java:178) ~[commons-app-2.1.0.jar:na]
        at cz.cuni.mff.xrg.odcs.commons.app.pipeline.transfer.ImportService.getImportedInformation(ImportService.java:314) ~[commons-app-2.1.0.jar:na]
        at cz.cuni.mff.xrg.odcs.commons.app.pipeline.transfer.ImportService$$FastClassByCGLIB$$9c8f1769.invoke(<generated>) ~[cglib-3.0.jar:na]
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[cglib-3.0.jar:na]
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618) ~[spring-aop-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at cz.cuni.mff.xrg.odcs.commons.app.pipeline.transfer.ImportService$$EnhancerByCGLIB$$44a8ffe3.getImportedInformation(<generated>) ~[cglib-3.0.jar:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.dialog.PipelineImport$3.uploadFinished(PipelineImport.java:175) ~[PipelineImport$3.class:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:979) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.ui.Upload.fireUploadSuccess(Upload.java:888) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.ui.Upload$2.streamingFinished(Upload.java:1150) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.communication.FileUploadHandler.streamToReceiver(FileUploadHandler.java:597) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.communication.FileUploadHandler.handleFileUploadValidationAndData(FileUploadHandler.java:453) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.communication.FileUploadHandler.doHandleSimpleMultipartFileUpload(FileUploadHandler.java:403) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.communication.FileUploadHandler.handleRequest(FileUploadHandler.java:285) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1406) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305) [vaadin-server-7.3.7.jar:7.3.7]
        at cz.cuni.mff.xrg.odcs.frontend.ODCSSSOApplicationServlet.service(ODCSSSOApplicationServlet.java:98) [ODCSSSOApplicationServlet.class:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722) [tomcat-servlet-api-3.0.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:183) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:100) [cas-client-core-3.3.3.jar:3.3.3]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) [spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.config.debug.DebugFilter.invokeWithWrappedRequest(DebugFilter.java:69) [spring-security-config-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.security.config.debug.DebugFilter.doFilter(DebugFilter.java:58) [spring-security-config-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200) [tomcat-coyote-7.0.28.jar:7.0.28]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579) [tomcat-coyote-7.0.28.jar:7.0.28]
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-coyote-7.0.28.jar:7.0.28]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: com.thoughtworks.xstream.converters.ConversionException: No field 'organization' found in class 'cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline' : No field 'organization' found in class 'cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline'
---- Debugging information ----
message             : No field 'organization' found in class 'cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline'
cause-exception     : com.thoughtworks.xstream.converters.reflection.MissingFieldException
cause-message       : No field 'organization' found in class 'cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline'
class               : cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline
required-type       : cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline
converter-type      : com.thoughtworks.xstream.converters.javabean.JavaBeanConverter
path                : /cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline/organization
version             : not available
-------------------------------
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79) ~[xstream-1.4.7.jar:1.4.7]
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65) ~[xstream-1.4.7.jar:1.4.7]
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66) ~[xstream-1.4.7.jar:1.4.7]
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50) ~[xstream-1.4.7.jar:1.4.7]
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134) ~[xstream-1.4.7.jar:1.4.7]
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32) ~[xstream-1.4.7.jar:1.4.7]
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185) ~[xstream-1.4.7.jar:1.4.7]
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1169) ~[xstream-1.4.7.jar:1.4.7]
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1133) ~[xstream-1.4.7.jar:1.4.7]
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1075) ~[xstream-1.4.7.jar:1.4.7]
        at cz.cuni.mff.xrg.odcs.commons.app.pipeline.transfer.ImportService.loadPipeline(ImportService.java:174) ~[commons-app-2.1.0.jar:na]
        ... 74 common frames omitted
Caused by: com.thoughtworks.xstream.converters.reflection.MissingFieldException: No field 'organization' found in class 'cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline'
        at com.thoughtworks.xstream.converters.javabean.PropertyDictionary.propertyDescriptor(PropertyDictionary.java:98) ~[xstream-1.4.7.jar:1.4.7]
        at com.thoughtworks.xstream.converters.javabean.BeanProvider.getProperty(BeanProvider.java:186) ~[xstream-1.4.7.jar:1.4.7]
        at com.thoughtworks.xstream.converters.javabean.BeanProvider.propertyDefinedInClass(BeanProvider.java:134) ~[xstream-1.4.7.jar:1.4.7]
        at com.thoughtworks.xstream.converters.javabean.JavaBeanConverter.unmarshal(JavaBeanConverter.java:130) ~[xstream-1.4.7.jar:1.4.7]
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72) ~[xstream-1.4.7.jar:1.4.7]
        ... 84 common frames omitted
2015-07-10 12:24:57,809 [ajp-bio-28009-exec-2] WARN  c.c.m.xrg.odcs.frontend.ODCSSSOApplicationServlet - Request (59) finished processing in: 1079 ms - LONG RESPONSE
2015-07-10 12:24:57,809 [ajp-bio-28009-exec-2] DEBUG c.c.m.xrg.odcs.frontend.ODCSSSOApplicationServlet - Request (/unifiedviews/APP/UPLOAD/0/43/action/db185d37-605c-4092-b584-1a66cc53b4dd) URI
2015-07-10 12:24:57,820 [ajp-bio-28009-exec-2] INFO  Spring Security Debugger -
```

**Comment by Jan-Marcek** [comment]
!!!! when I removed field from pipeline.xml
```
  <organization>
    <name>comsode</name>
  </organization>

```
then it worked.

**Comment by skrchnavy** [comment]
Connect UnifiedViews/Core#447

**Comment by skrchnavy** [comment]
UnifiedViews/Core#447 release so it shall work in v1.1.1 of ODN

**Comment by eea71** [comment]
seems in pre-release 1.1.2 is ok

**Comment by skrchnavy** [comment]
@eea71 to retest in released version
