### ISSUE TITLE
NullPointerException when NULL value is processed by relational DPUs

### ISSUE THREAD

**Issue by hanecak** [OpenDataNode/open-data-node#263]
PROBLEM 2 from support mailing list posting (https://groups.google.com/forum/#!msg/odn-support/csP2S_wyz5I/hVqym_qeBQAJ):

It seems that if a relational table created by  uv-relationalFromSQL contains a column with NULL values any cascading relational DPU fails (e.g. relationalToCKAN or relationalToRFD) always fail 

"Failed to create resource / datastore elenco_impianti_sportivi for table INTERNAL_IMPIANTI_SPORTIVI

Stack trace:
java.lang.NullPointerException Value in JsonObjects name/value pair cannot be null
   at org.glassfish.json.JsonObjectBuilderImpl.validateValue(JsonObjectBuilderImpl.java:164)
   at org.glassfish.json.JsonObjectBuilderImpl.add(JsonObjectBuilderImpl.java:88)
   at org.opendatanode.plugins.loader.relationaltockan.RelationalToCkanHelper.buildRecordsJson(RelationalToCkanHelper.java:223)
   at org.opendatanode.plugins.loader.relationaltockan.RelationalToCkan.createDatastoreFromTable(RelationalToCkan.java:452)
   at org.opendatanode.plugins.loader.relationaltockan.RelationalToCkan.innerExecute(RelationalToCkan.java:210)
   at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:133)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:248)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:386)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:468)
   at java.lang.Thread.run(Thread.java:745)"

**Comment by eea03** [comment]
Fixed in https://github.com/OpenDataNode/UVPlugin-relationalDiffToCKAN/pull/11 and https://github.com/OpenDataNode/UVPlugin-relationalToCKAN/pull/17

Same problem for both RelationalToCkan and RelationalDiffToCkan DPUs

**Comment by eea03** [comment]
I have not found any problem with RelationalToRdf DPU, I couldn't reproduce any problems with table containing null values

**Comment by hanecak** [comment]
Fixes included in ODN 1.5.0 (ODN Plugins v1.3.0).

**Comment by hanecak** [comment]
We forgot to merge the fix from develop to master thus - sadly - ODN 1.5.0 does not contain the fix. So I'm reopening the issue.

See also https://github.com/OpenDataNode/UVPlugin-relationalDiffToCKAN/pull/12 .

**Comment by eea03** [comment]
Fixes are included in ODN_UV Plugins release v1.3.1
https://github.com/OpenDataNode/ODN-UV-Plugins/releases/tag/ODN_v1.3.1

**Comment by hanecak** [comment]
Fixes shipped also in ODN-UV-Plugins 1.4.0 (https://github.com/OpenDataNode/ODN-UV-Plugins/releases/tag/ODN_v1.4.0) which is part of ODN 1.6.0 .
